# Taskfile.yml
version: '3'

vars:
  APP_NAME: gptprep
  VERSION: v1.0.9

tasks:
  run:
    desc: Start gptprep locally with optional flags
    cmds:
      - go run ./cmd {{.CLI_ARGS}}

  release:
    desc: Tag the new version and push it to GitHub
    cmds:
      - git tag -a "{{.VERSION}}" -m "Release VERSION {{.VERSION}} of {{.APP_NAME}}"
      - git push origin "{{.VERSION}}"
