name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21' # Specify the Go version you want to use for building

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build binary
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o "gptprep-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv "gptprep-${{ matrix.goos }}-${{ matrix.goarch }}" "gptprep-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
        fi

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: gptprep-${{ matrix.goos }}-${{ matrix.goarch }}
        path: gptprep-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v1
        - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
